GlobalParameters:
  MinimumRequiredVersion: 4.2.0
  NumElementsToValidate: -1
  KernelTime: True
  DataInitTypeD : 0
  DataInitTypeC : 0

BenchmarkProblems:
  - # zgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: z
      DestDataType: z
      ComputeDataType: z
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Source"]
      ForkParameters:
        - GlobalSplitU: [1]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
        - WorkGroup:
          - [  32,  4, 1 ]
        - DepthU: [ 8 ]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1], [1], [1], [8,1,32] ]

#LibraryLogic:
#    ScheduleName: "vega10"
#    DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860", "Device 6861", "Vega 10 XTX [Radeon Vega Frontier Edition]", "Vega [Radeon RX Vega]"]
#    ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

#LibraryClient:
