# This Dockerfile provides a starting point for a ROCm installation of Tensile.

# Parameters related to building hip
ARG base_image

FROM ${base_image}
LABEL maintainer="shuang.huang@amd.com"

USER root
ARG user_uid

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cmake \
    ca-certificates \
    doxygen \
    git \
    graphviz \
    pkg-config \
    libnuma1 \
    llvm-6.0-dev \
    libboost-all-dev \
    zlib1g-dev \
    libomp-dev \
    vim \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
#    python3 \
#    python3-dev \
#    python3-pip \
#    python3-pytest \
#    python3-setuptools \
#    python3-yaml \

# The version of MessagePack supplied in Ubuntu 16.04 is old and won't work,
# so we'll manually download and install the DEB files
RUN curl -O http://ftp.us.debian.org/debian/pool/main/m/msgpack-c/libmsgpack-dev_3.0.1-3_amd64.deb \
         -O http://ftp.us.debian.org/debian/pool/main/m/msgpack-c/libmsgpackc2_3.0.1-3_amd64.deb
RUN dpkg -i libmsgpack-dev_3.0.1-3_amd64.deb libmsgpackc2_3.0.1-3_amd64.deb

RUN pip3 install --upgrade pip && \
    pip3 install setuptools --upgrade && \
    pip3 install wheel && \
    pip3 install tox pyyaml msgpack && \
    pip3 install numpy pandas matplotlib tqdm pyarrow scikit-learn --upgrade
